### ISSUE TITLE
Ray version

### ISSUE THREAD

**Issue by wzf2022** [NVlabs/handover-sim2real#3]
Thanks for your wonderful work!
I wonder what is the version of the package Ray? I try some versions but it cannot start...

**Comment by sammychristen** [comment]
It should work with ray version 2.7.1 
What version are you using? Can you be a bit more specific about the error you are getting?

**Comment by wzf2022** [comment]
Thanks! I try some versions like 0.8.5 or 2.0.  2.7.1 works!
